application: skej-prod
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# main
- url: .*
  script: home.app
# static dirs
# --- images
- url: /i/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)
# --- javascript
- url: /j
  static_dir: static/js
# --- css
- url: /c
  static_dir: static/css
# --- html
- url: /h
  static_dir: static/html
  expiration: '365d'

libraries:
- name: jinja2
  version: latest
